### PR TITLE
General fixes (version, recents, project)

### LINKED ISSUE #170: Duplicates in recent files
image

Expected behaviour: no duplicates in recent files
Observed behaviour: duplicates in recent files

### PR DESCRIPTION
**Pull request by toinehartman**
Fix some small things.
- Version number bumped.
- Clear recents (closes #170).
- Project cleanup.

### CODE REVIEW

File: src/main/java/programminglife/gui/controller/GuiController.java [hunk 1]
```diff
@@ -179,6 +179,7 @@ private void initRecent() {
         }
         if (recentFile != null) {
             try (Scanner sc = new Scanner(recentFile)) {
+                menuRecent.getItems().clear();
```
Comment (YDutchy) [inline src/main/java/programminglife/gui/controller/GuiController.java]: Thanks for adding this! I hadn't had any problems with duplicated, and I couldn't come up with a way to fix it. Well done!
